### ISSUE TITLE
Use of async functions

### ISSUE THREAD

**Issue by mcollina** [heply/fastify-totp#1]
I don't think the async functions are needed, can you confirm?

**Comment by zuck** [comment]
@mcollina yes, you're right: at the moment they are not strictly necessary but they have been left as async to avoid breaking changes to the public API in the case we need to switch to an async computation. Does it make sense for you? Thank you for your feedback!

**Comment by mcollina** [comment]
I would highly recommended against this. This type of pattern leads to having all functions as async functions, with hundreds of promises allocated for no good reasons :/.

**Comment by zuck** [comment]
@mcollina we switched to sync methods where possible with v0.1.0. Can you confirm the resolution of this issue, please? Thank you!

**Comment by mcollina** [comment]
Good work!
